//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinrShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblProductItem
    {
        public int ItemID { get; set; }
        [Required(ErrorMessage = "Item Name is required.")]
        [StringLength(50, ErrorMessage = "Item Name should not be greater than 50 chracter.")]
        [Display(Name = "Item Name")]
        public string ItemName { get; set; }
        [Required(ErrorMessage = "Price is required.")]
        [Display(Name = "Item Price")]
        public Nullable<decimal> Price { get; set; }
        [Display(Name = "Item Image")]
        public string Image { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Image is required.")]
        public HttpPostedFileBase ImageUpload { get; set; }

        public tblProductItem()
        {
            Image = "Image.png";
        }
    }
}
